### ISSUE TITLE
Upgrading Angular sample from 5.2.0 to 6.0.0 results in a compilation error

### ISSUE THREAD

**Issue by mraible** [okta/okta-angular#107]
### Describe the bug?

When upgrading from Okta Angular 5.2.0 to 6.0.0, there is a compilation error.

```
Error: src/app/profile/profile.component.ts:30:42 - error TS2339: Property 'claims' does not exist on type 'Token'.
  Property 'claims' does not exist on type 'RefreshToken'.

30     this.claims = Object.entries(idToken.claims).map(entry => ({ name: entry[0], value: entry[1] }));
```

Code:

```
async ngOnInit() {
  const idToken = await this.oktaAuth.tokenManager.get('idToken');
  this.claims = Object.entries(idToken.claims).map(entry => ({ name: entry[0], value: entry[1] }));
}
```

See https://github.com/okta-samples/okta-angular-sample/pull/564. 

### What is expected to happen?

Compilation succeeds. 

### What is the actual behavior?

Compilation fails.

### Reproduction Steps?

Install the Okta CLI and run the following commands:

```
okta start angular -b fix-vulnerabilities
cd angular
npm install
npm start
```

### SDK Versions

6.0.0

### Execution Environment

Node 16

**Comment by denysoblohin-okta** [comment]
Please do a type cast to `IDToken`
```js
import { IDToken } from '@okta/okta-auth-js';
const idToken: IDToken = await tokenManager.get('idToken') as IDToken;
```
as described in readme
https://github.com/okta/okta-auth-js#usage-with-typescript
